### ISSUE TITLE
v1.1.1: toBeRejectedWith fails with jasmine.any(String)

### ISSUE THREAD

**Issue by marcin-wosinek** [bvaughn/jasmine-promise-matchers#10]
First of all, thanks for all the work done on the module.

I've noticed regression after update from 0.5.0 to 1.1.1. I've been using generic matcher in my tests:
```javascript
expect(promise).toBeRejectedWith(jasmine.any(String));
```
which currently fails with:
`Expected <string content> to be {}`
downgrading to 0.0.5 fixed the issue. 

it looks that issue is caused by differences between checking result in:
* 0.0.5 https://github.com/bvaughn/jasmine-promise-matchers/blob/0.0.5/src/main.js#L58
* 1.1.1 https://github.com/bvaughn/jasmine-promise-matchers/blob/1.1.1/source/source.js#L60

**Comment by bvaughn** [comment]
Hello! Thank you for the kind words. :)

I'm sorry you've encountered a regression. I'll try to take a look at it after work one evening this week. Thanks for the info you've provided!

**Comment by bvaughn** [comment]
Hi again @marcin-wosinek.

Thanks for bringing this issue to my attention. Release [1.1.2](https://github.com/bvaughn/jasmine-promise-matchers/releases/tag/1.1.2) should have a fix for you!

**Comment by marcin-wosinek** [comment]
Thanks a lot!
