### ISSUE TITLE
I've created a SublimeText snippets package

### ISSUE THREAD

**Issue by Hyzual** [bvaughn/jasmine-promise-matchers#11]
Hi,

First of all sorry to open an issue, I didn't know how else to contact you through Github. Feel free to close it anytime :).
Anyway, I just wanted to let you know that since I use Jasmine Promise Matchers a lot, I've published a Sublime Text package of snippets for it here: https://packagecontrol.io/packages/Jasmine%20Promise%20Matchers
It makes it easier and faster to use the expectations. I can give you push access to the repo if you're interested.

**Comment by bvaughn** [comment]
Hi @Hyzual!

No problem about filing a bug to contact me. Github does kind of lack a messaging system. :)

I'm happy to hear that you're getting a lot of use out of the library. And a Sublime extension is a neat idea. I don't have any initial suggestions for additions that would require push access, but if you'd like to grant me access I'd be happy to commit anything I think of.

In the meanwhile, I'll update the main README (for this library) to link to your Sublime extension.

PS. Leaving this bug open to remind myself to make that Wiki update when I get back to my personal computer.

**Comment by bvaughn** [comment]
Gave you props and linked to the plugin on the main README. :)

Thanks!
