### ISSUE TITLE
Help integrating with Karma

### ISSUE THREAD

**Issue by mischkl** [bvaughn/jasmine-promise-matchers#12]
Hi, as this is meant to be used with Angular the chances seem good that it is also going to be used in combination with Karma. However it's unclear from the documentation how to set Karma up to incorporate these matchers. I did get it working by adding it to the list of files in the karma config:

```js
files: [
  "node_modules/jasmine-promise-matchers/dist/jasmine-promise-matchers.js"
...
]
```

but I wonder if there isn't a "better way", e.g. something like this: https://github.com/JamieMason/karma-jasmine-matchers

In any case it would at least be nice to document the need to add this line to the list of files in the Karma config.

Thanks for the awesome library! :)

**Comment by bvaughn** [comment]
Thanks for the suggestion Michael :)

Docs have been updated!
