### ISSUE TITLE
calling `.toBe*With` with a primitive triggers error

### ISSUE THREAD

**Issue by jrencz** [bvaughn/jasmine-promise-matchers#14]
```js
expect(promise).toBeResolvedWith(null);
```

triggers error:

```
TypeError: 'null' is not an object (evaluating 'data.asymmetricMatch')
	    at /Volumes/Projects/.../lib/jasmine-promise-matchers/dist/jasmine-promise-matchers.js:24
	    at /Volumes/Projects/.../lib/jasmine-promise-matchers/dist/jasmine-promise-matchers.js:50
	    at /Volumes/Projects/.../lib/jasmine-promise-matchers/dist/jasmine-promise-matchers.js:114
	    at /Volumes/Projects/.../specs.spec.js:1
```

apparently non-objects have to be tested with:

```js
let result;
const promise = someFunction().then(value => {
  result = value;
});
expect(promise).toBeResolved();
// implicit digest here
expect(result).toBe(null);
```

**Comment by bvaughn** [comment]
When you say "a primitive" are you referring to a native ES6 Promise? If so... this particular library was intended for testing Angular's flavor of promises (those created by [`$q`](https://docs.angularjs.org/api/ng/service/$q)). Testing native ES6 Promises is more inline with another library of mine, [`jasmine-es6-promise-matchers`](https://github.com/bvaughn/jasmine-es6-promise-matchers).

**Comment by bvaughn** [comment]
If you can provide a little more context, @jrencz, I'll be happy to help :)

PS. I apologize in advance if I'm sounding a little dense. Just returned from a trip from China less than 24 hours ago and I'm pretty jet-lagged still.

**Comment by jrencz** [comment]
I'm referring to a non-object value: string, number or null.

**Comment by bvaughn** [comment]
Oh? You're passing a string/number/null *instead of* a Promise to the expect? Something like...

```javascript
var notAPromise = 123;
expect(notAPromise).toBeResolvedWith(null);
```

Why would you do that? Or am I still misunderstanding? I'm afraid I might need more of a code sample from you to understand what's going on.

If I'm understanding you correctly, then I don't think it's something this library should really support. The library is intended for working with promises. Maybe you could structure your test to first assert that what you're dealing with *is actually a Promise* like so:

```javascript
expect(maybePromise).toBePromise();
expect(toBePromise).toBeResolvedWith(123);
```

**Comment by jrencz** [comment]
No: I'm passing a promise to expect and a primitive to the matcher - just as I described in the issue.

Promise can be resolved with any value, including a non-object, primitive value. In such case the matcher rises an error which it shouldn't.

**Comment by bvaughn** [comment]
Hmm. I didn't think you were saying that because that works fine. (The tests here in the Github project even try that.)

```javascript
var deferred = $q.defer();
deferred.reject('foobar');
expect(deferred.promise).toBeRejectedWith(jasmine.any(String));
```

Again... will you give me more of a complete coding example?

**Comment by bvaughn** [comment]
I'm guessing you've gotten this sorted out, since you haven't gotten back to me. But if I'm wrong- please provide me with a GH snippet or complete code example and I'd be happy to take a look.
