### ISSUE TITLE
Migration from the version 1.1.2 to the version 1.1.3 breaks some tests

### ISSUE THREAD

**Issue by pustun** [bvaughn/jasmine-promise-matchers#16]
Some tests that worked fine with version 1.1.2 are now red.

Code bellow fails in version 1.1.3

expect(response).toBeResolvedWith([serverResponse]);

response is a promise that was resolved with an array.

Switching back to the version 1.1.2 fixes the issue

**Comment by pustun** [comment]
I found the issue. Version 1.1.3 compares objects differently. One of the objects has extra property. Version 1.1.2 considered those objects to be equivalent but the version 1.1.3 does not.

**Comment by bvaughn** [comment]
Hi @pustun. Sorry for the non-backwards compatible change in 1.1.3. I was unaware of it or I would have gone with a major version number. My apologies.
