### ISSUE TITLE
'$injector' is not being injected in minified version.

### ISSUE THREAD

**Issue by mabilalmirza** [bvaughn/jasmine-promise-matchers#18]
Following error occurs when minified version is used, 

http://errors.angularjs.org/1.4.5/$injector/unpr?p0=eProvider%20%3C-%20e

I think this is because when following line were minified, $injector was renamed to 'e'.

```
installPromiseMatchers = function() {
    inject(function($injector) {
      $scope = $injector.get('$rootScope');
    });
  };
```

Here's the minified code

    installPromiseMatchers=function(){inject(function(e){t=e.get("$rootScope")})}

___
Issue observed in v2.0.0

**Comment by bvaughn** [comment]
Thanks for reporting this issue. Sorry for the inconvenience.

Version [2.0.1](https://github.com/bvaughn/jasmine-promise-matchers/releases/tag/2.0.1) is available for you now with a fix.
