### ISSUE TITLE
Missing global PhantomJS for contribution

### ISSUE THREAD

**Issue by Hyzual** [bvaughn/jasmine-promise-matchers#22]
Hi,

I was trying to set up the dev environment like you explain in the "Contributing" section, but `grunt` always failed. It seems that the `karma-phantomjs-launcher` is missing an installation of `phantomjs` somewhere.

The following solution worked for me: 

```bash
npm install --global phantomjs-prebuilt
export PHANTOMJS_BIN=/usr/local/bin/phantomjs
```

A PR is on the way to add this to the README.

**Comment by bvaughn** [comment]
Hi @Hyzual,

My apologies for the setup hiccup. Thank you for contributing a PR :)
