### ISSUE TITLE
Allow opt-out of implicit flush introduced in 2.1.0

### ISSUE THREAD

**Issue by jrencz** [bvaughn/jasmine-promise-matchers#26]
Feature introduced in #25 is useful but one may want to test if something is NOT happening until timeout or request is flushed. Please consider adding an opt-out from that behaviour.

I do have some tests like this.

cc @casmith

**Comment by bvaughn** [comment]
Perhaps @casmith or @carlin-q-scott (or you, @jrencz?) would be willing to add this functionality? I'd be happy to review it and create a new release.

**Comment by casmith** [comment]
That's a fair point. What would be the idea solution for this? A wrapper for toBeResolved such as `toBeResolvedWithFlush()` that does the implicit flushing up front? 

Or an options object? 

e.g., 
`expect(promise).toBeResolved({flush: true})` (default: false)

I was actually thinking about this approach for opting out of the $scope.$digest as well. 

`expect(promise).toBeResolved({$digest: false})` (default: true)

**Comment by jrencz** [comment]
We should probably discuss the api first. The first thought that comes to my mind is to pass a second argument to the matcher. Let this be an object with appropriate key having a boolean value (i.e. a named param if we consider es2015 destructuring). This way we can add new flags at will

**Comment by jrencz** [comment]
The has to be a way to opt-out globally (or better: within current suite so it can be set in beforeEach)

**Comment by carlin-q-scott** [comment]
I'd prefer to opt out via a configuration method that can be called from anywhere in a test (beforeEach, it). I think in most cases people will want the flush/digest but some tests may need it to not run.

It would be handy to have an example test where this behavior is needed though, for clarification sakes, as I'd expect the $httpBackend.expect methods to cover all of the situations just fine.

**Comment by al-the-x** [comment]
Seems like a convenient API hook exists for this: `installPromiseMatchers`. Since it currently has to be executed in the `beforeEach` after the module is initialized, it could accept a config object and merge that into the per-test defaults... Thoughts?

**Comment by casmith** [comment]
@al-the-x This seems reasonable. I raised a PR here: https://github.com/bvaughn/jasmine-promise-matchers/pull/36

**Comment by bvaughn** [comment]
Going out as 2.5.0
