### ISSUE TITLE
Implicit flush: don't try/catch if promise is already resolved

### ISSUE THREAD

**Issue by jrencz** [bvaughn/jasmine-promise-matchers#27]
Kind of perf opt: we can check if condition is passed before running (somewhat costly) try/catch twice.

If promise is supposed to be resolved and it is then it's state won't change.

Test may be rerun after first try/catch as well

Rationale: unit tests should be as fast as possible. Even if we gain 1% of execution time by doing this it's worth the effort IMHO

**Comment by jrencz** [comment]
Related: #26

**Comment by bvaughn** [comment]
As with #26, I'd welcome a PR for this :) I probably won't get to it any time soon. Kind of swamped with other work at the moment.
