### ISSUE TITLE
Published version of 2.1.0 has no changes in the dist folder

### ISSUE THREAD

**Issue by casmith** [bvaughn/jasmine-promise-matchers#31]
It looks like the full grunt build wasn't run before 2.1.0 was published to npm. The previous version of the scripts are still present in dist/.

**Comment by bvaughn** [comment]
Oh. Yikes. I'll put out another release momentarily.

**Comment by bvaughn** [comment]
Although I'm confused by the existence of issues #26 and #27 if the previous / cached version was released...

**Comment by bvaughn** [comment]
2.2.0 was just pushed out.
