### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by marcin-wosinek** [bvaughn/jasmine-promise-matchers#5]
Hey,

Thanks a lot for great package - it's exactly the thing I was missing. I've noticed fail message for reject is pretty non standard. For that code:

    expect(current).toBeRejectedWith(message); // current rejects to undefined
    expect(undefined).toEqual(message);

I get following errors:

    Expected undefined to equal 'lorem Ipsum'.
    Expected 'lorem Ipsum' to equal undefined.

note: I'm using head from *develop*

**Comment by marcin-wosinek** [comment]
the `src/main.js` and `dist/jasmine-promise-matchers.js` looks the same, but they differ at promise reject comparison:
https://github.com/bvaughn/jasmine-promise-matchers/blob/develop/dist/jasmine-promise-matchers.js#L33

**Comment by bvaughn** [comment]
You're welcome. I appreciate the catch and the fix! I'll push another release out in a few moments. :)

**Comment by bvaughn** [comment]
Version 0.0.5 is out with your fix. Thanks again!
