### ISSUE TITLE
Unresolved Promises not Detected

### ISSUE THREAD

**Issue by redpoptarts** [bvaughn/jasmine-promise-matchers#7]
.toBeResolved() passes even when promise is never resolved (left unfulfilled).

This is because the method only adds an expect inside the resolve/reject of  the promise.  If the promise is neither resolved nor rejected, no expectations are made, and the matcher has already passed.

I have created a pull request which adds a hacky but simple stack that will allow you to detect if any of the matchers failed to fulfill their promises.

**Comment by bvaughn** [comment]
Hey Caleb!

Looks like you're modifying an older version of the library. I'd actually already addressed this issue in master ([see here](https://github.com/bvaughn/jasmine-promise-matchers/commit/e045501f1c5ef16c3392a82ebe87dd6c32f7dccf)) by forcing a root-scope-digest, but had not yet released an updated version.

That's my bad. I'll try to release an update this evening.

**Comment by bvaughn** [comment]
This issue has been fixed in the latest release- https://github.com/bvaughn/jasmine-promise-matchers/releases/tag/1.0.0

Thanks for reporting! :)
